define({
    "Studies": "Opinnot",
    "stud1_year": "2012",
    "stud1_desc": "Tampereen ammattikorkeakoulu, Kuvataiteen koulutusohjelma",
    "stud2_year": "2012",
    "stud2_desc": "Opiskelijavaihto, Hanze Hogeschool Groningen, Fine Art department, Hollanti",
    "stud3_year": "2012",
    "stud3_desc": "Pohjois-Karjalan ammattiopisto, Joensuu, Kivi- ja metalliseppä",
    "SoloExhibitions": "Yksityisnäyttelyt",
    "soloEx1_year": "2013",
    "soloEx1_desc": "Myllytys, B-galleria, Turku",
    "GroupExhibitions": "Ryhmänäyttelyt",
    "groupEx1_year": "2013",
    "groupEx1_desc": "SKjL -vuosinäyttely, Voipaalan Taidekeskus, Sääksmäki",
    "groupEx2_year": "2013",
    "groupEx2_desc": "Art of Basware, Nuoren kuvataiteen kilpailu, Musiikkitalo, Helsinki",
    "groupEx3_year": "2012",
    "groupEx3_desc": "Vaahtokarkki-kutsunäyttely, Haiharan taidekeskus, Tampere",
    "groupEx4_year": "2012",
    "groupEx4_desc": "ERO-lopputyönäyttely, Mältinrannan taidekeskus, Tampere",
    "groupEx5_year": "2011",
    "groupEx5_desc": "Näkymä, Raaka taide, Akaa",
    "groupEx6_year": "2010",
    "groupEx6_desc": "Who?, Galleria Minerva, Groningen, Hollanti",
    "groupEx7_year": "2010",
    "groupEx7_desc": "Megagagaa, Galleria Nottbeck, Tampere",
    "groupEx8_year": "2009",
    "groupEx8_desc": "Lyhyt videokirjasto, Galleria Emil, Tampere",
    "groupEx9_year": "2008",
    "groupEx9_desc": "Jotain sanottavaa, Ikuinen Galleria, Tampere",
    "Events": "Tapahtumat",
    "event1_year": "2010",
    "event1_desc": "4m²-projekti, Tampere",
    "event2_year": "2009",
    "event2_desc": "4m²-projekti, Galleria Hippolyten järjestämä, Yhteinen leikki -tapahtuma, Helsinki",
    "event3_year": "2008",
    "event3_desc": "Talvenvaloa, Nokia",
    "event4_year": "2008",
    "event4_desc": "Liitupiirustus, Tampere",
    "Residencies": "Residenssit",
    "residence1_year": "2012",
    "residence1_desc": "Hämeen taidetoimikunta, Edinburgh, Skotlanti",
    "Memberships": "Jäsenyydet",
    "membership1": "Taidemaalariliitto, kokelasjäsen"
});
