define({
    "Upcoming": "Tulossa",
    "upcomingEx1_date": "1.12. - 31.12.2014",
    "upcomingEx1_desc": "Tänään, Galleria SEINÄ, Helsinki",
    "Studies": "Opinnot",
    "stud1_year": "2012",
    "stud1_desc": "Kuvataiteilija AMK, Tampereen ammattikorkeakoulu, Tampere",
    "stud2_year": "2011",
    "stud2_desc": "Opiskelijavaihto, Hanze Hogeschool Groningen, Fine Art, Hollanti",
    "stud3_year": "2008",
    "stud3_desc": "Käsityömuotoilija, Pohjois-Karjalan ammattiopisto, Joensuu",
    "SoloExhibitions": "Yksityis- ja ryhmänäyttelyt",
    "soloEx4_year": "2015",
    "soloEx4_desc": "Läsnä, yhdessä Liisa Hietasen kanssa, Poriginal Galleria, Pori",
    "soloEx3_year": "2014",
    "soloEx3_desc": "Tänään, Galleria SEINÄ, Helsinki",
    "soloEx2_year": "2014",
    "soloEx2_desc": "TOISTO, yhdessä Laura Hetemäen kanssa, Seinäjoen taidehalli, Seinäjoki",
    "soloEx1_year": "2013",
    "soloEx1_desc": "Myllytys, B-galleria, Turku",
    "GroupExhibitions": "Ryhmänäyttelyt",
    "groupEx13_year": "2014",
    "groupEx13_desc": "Punaista ja makeaa, Voipaalan taidekeskus, Sääksmäki",
    "groupEx12_year": "2013",
    "groupEx12_desc": "Muotokuva, Lahden taidemuseo, Lahti",
    "groupEx11_year": "2013",
    "groupEx11_desc": "Suomen pohjoismainen taideliitto - Pohjoinen rakkaus, Taidekeskus Haihatus, Joutsa",
    "groupEx10_year": "2013",
    "groupEx10_desc": "Y-Festivaali, Näsilinna, Tampere",
    "groupEx1_year": "2013",
    "groupEx1_desc": "SKjL -vuosinäyttely, Voipaalan Taidekeskus, Sääksmäki",
    "groupEx2_year": "2013",
    "groupEx2_desc": "Art of Basware, Nuoren kuvataiteen kilpailu, Musiikkitalo, Helsinki",
    "groupEx3_year": "2012",
    "groupEx3_desc": "Vaahtokarkki-kutsunäyttely, Haiharan taidekeskus, Tampere",
    "groupEx4_year": "2012",
    "groupEx4_desc": "ERO-lopputyönäyttely, Mältinrannan taidekeskus, Tampere",
    "groupEx5_year": "2011",
    "groupEx5_desc": "Näkymä, Raaka taide, Akaa",
    "groupEx6_year": "2010",
    "groupEx6_desc": "Who?, Galleria Minerva, Groningen, Hollanti",
    "groupEx7_year": "2010",
    "groupEx7_desc": "Megagagaa, Galleria Nottbeck, Tampere",
    "groupEx8_year": "2009",
    "groupEx8_desc": "Lyhyt videokirjasto, Galleria Emil, Tampere",
    "groupEx9_year": "2008",
    "groupEx9_desc": "Jotain sanottavaa, Ikuinen Galleria, Tampere",
    "Events": "Tapahtumat",
    "event1_year": "2010",
    "event1_desc": "4m² -projekti, Tampere Art Factory, Tampere",
    "event2_year": "2009",
    "event2_desc": "4m² -projekti, Galleria Hippolyten järjestämä Yhteinen leikki -tapahtuma, Helsinki",
    "event3_year": "2008",
    "event3_desc": "Talvenvaloa, Nokia",
    "event4_year": "2008",
    "event4_desc": "Liitupiirustus, Tampere",
    "event5_year": "2014",
    "event5_desc": "Großes Treffen - Suuri kokous -kuratointitapahtuma, Berliini",
    "Residencies": "Residenssit",
    "residence1_year": "2012",
    "residence1_desc": "Hämeen taidetoimikunta, Edinburgh, Skotlanti",
    "Memberships": "Jäsenyydet",
    "membership1": "Taidemaalariliitto"
});
