define({
    "root": {
        "Studies": "Studies",
        "stud1_year": "2012",
        "stud1_desc": "BA, Tampere University of Applied Sciences, School of Art and Media, Fine Art Programme",
        "stud2_year": "2012",
        "stud2_desc": "Student Exchange at Hanze Hogeschool Groningen, Fine Art, The Netherlands",
        "stud3_year": "2008",
        "stud3_desc": "North Karelia College, Joensuu, Art and Craft",
        "SoloExhibitions": "Solo Exhibitions",
        "soloEx1_year": "2013",
        "soloEx1_desc": "B-gallery, Turku, Finland",
        "GroupExhibitions": "Group Exhibitions",
        "groupEx1_year": "2013",
        "groupEx1_desc": "SKjL 2013, Voipaala Art Centre, Sääksmäki, Finland",
        "groupEx2_year": "2013",
        "groupEx2_desc": "The Art of Basware, Music Centre, Helsinki, Finland",
        "groupEx3_year": "2012",
        "groupEx3_desc": "Vaahtokarkki, Haihara Art Centre, Tampere, Finland",
        "groupEx4_year": "2012",
        "groupEx4_desc": "ERO, Diploma work exhibition, Mältinranta Art Centre, Tampere, Finland",
        "groupEx5_year": "2011",
        "groupEx5_desc": "Raaka taide, Näkymä, Akaa, Finland",
        "groupEx6_year": "2010",
        "groupEx6_desc": "Who?, Gallery Minerva, Groningen, The Netherlands",
        "groupEx7_year": "2010",
        "groupEx7_desc": "Megagagaa, Gallery Nottbeck, Tampere, Finland",
        "groupEx8_year": "2009",
        "groupEx8_desc": "Lyhyt videokirjasto, Gallery Emil, Tampere, Finland",
        "groupEx9_year": "2008",
        "groupEx9_desc": "Jotain sanottavaa, Ikuinen Gallery, Tampere, Finland",
        "Events": "Events",
        "event1_year": "2010",
        "event1_desc": "4m²-projekti, Tampere Art Factory Tampere, Finland",
        "event2_year": "2009",
        "event2_desc": "4m²-projekti, Gallery Hippolyte's event, Helsinki, Finland",
        "event3_year": "2008",
        "event3_desc": "Talven valoa, Nokia, Finland",
        "event4_year": "2008",
        "event4_desc": "Liitupiirustus, Tampere, Finland",
        "Residencies": "Residencies",
        "residence1_year": "2012",
        "residence1_desc": "Arts Council of Häme, Edinburgh, Scotland",
        "Memberships": "Memberships",
        "membership1": "Finnish painter's union / Aspirant membership"
    },
    "fi": true
});