define({
    "root": {
        "Upcoming": "Upcoming",
        "upcomingEx1_date": "1.12. - 31.12.2014",
        "upcomingEx1_desc": "Today, Gallery SEINÄ, Helsinki, Finland",
        "Studies": "Studies",
        "stud1_year": "2012",
        "stud1_desc": "BA, Tampere University of Applied Sciences, School of Art and Media, Fine Art, Finland",
        "stud2_year": "2011",
        "stud2_desc": "Student Exchange at Hanzehogeschool Groningen, Fine Art, The Netherlands",
        "stud3_year": "2008",
        "stud3_desc": "North Karelia College, Art and Craft, Joensuu, Finland",
        "SoloExhibitions": "Solo Exhibitions",
        "soloEx2_year": "2014",
        "soloEx2_desc": "REPEAT, An exhibition with Laura Hetemäki, Seinäjoki Art Hall, Seinäjoki, Finland",
        "soloEx1_year": "2013",
        "soloEx1_desc": "Myllytys, B-gallery, Turku, Finland",
        "GroupExhibitions": "Group Exhibitions",
        "groupEx13_year": "2014",
        "groupEx13_desc": "Red And Sweet, Voipaala Art Centre, Sääksmäki, Finland",
        "groupEx12_year": "2013",
        "groupEx12_desc": "Muotokuva (Portrait), Lahti Art Museum, Lahti, Finland",
        "groupEx11_year": "2013",
        "groupEx11_desc": "Pohjoinen rakkaus (Northern Love), Art Centre Haihatus, Joutsa, Finland",
        "groupEx10_year": "2013",
        "groupEx10_desc": "Y-Festival, Tampere, Finland",
        "groupEx1_year": "2013",
        "groupEx1_desc": "SKjL 2013, Voipaala Art Centre, Sääksmäki, Finland",
        "groupEx2_year": "2013",
        "groupEx2_desc": "The Art of Basware, Music Centre, Helsinki, Finland",
        "groupEx3_year": "2012",
        "groupEx3_desc": "Vaahtokarkki, Haihara Art Centre, Tampere, Finland",
        "groupEx4_year": "2012",
        "groupEx4_desc": "ERO, Diploma work exhibition, Mältinranta Art Centre, Tampere, Finland",
        "groupEx5_year": "2011",
        "groupEx5_desc": "Raaka taide, Näkymä, Akaa, Finland",
        "groupEx6_year": "2010",
        "groupEx6_desc": "Who?, Gallery Minerva, Groningen, The Netherlands",
        "groupEx7_year": "2010",
        "groupEx7_desc": "Megagagaa, Gallery Nottbeck, Tampere, Finland",
        "groupEx8_year": "2009",
        "groupEx8_desc": "Lyhyt videokirjasto, Gallery Emil, Tampere, Finland",
        "groupEx9_year": "2008",
        "groupEx9_desc": "Jotain sanottavaa, Ikuinen Gallery, Tampere, Finland",
        "Events": "Events",
        "event1_year": "2010",
        "event1_desc": "4m²-projekti, Tampere Art Factory Tampere, Finland",
        "event2_year": "2009",
        "event2_desc": "4m²-projekti, Gallery Hippolyte's event, Helsinki, Finland",
        "event3_year": "2008",
        "event3_desc": "Talven valoa, Nokia, Finland",
        "event4_year": "2008",
        "event4_desc": "Liitupiirustus, Tampere, Finland",
        "event5_year": "2014",
        "event5_desc": "Großes treffen, Network Event, Berlin, Germany",
        "Residencies": "Residencies",
        "residence1_year": "2012",
        "residence1_desc": "Arts Council of Häme, Edinburgh, Scotland",
        "Memberships": "Memberships",
        "membership1": "Finnish painter's union / Aspirant membership",
        "membership2": "Tampere Artists' Association"
    },
    "fi": true
});