        "nameX": "Matti Jumps in to The Fog",
        "descX": "2013, oil on board, 40 cm x 50 cm",
        "nameX": "Kimi Has Cool Shades",
        "descX": "2013, oil on board, 37 cm x 50 cm",
        "nameX": "Young Danny",
        "descX": "2013, oil on board, 50 cm x 60 cm",
        "nameX": "Killer Shark",
        "descX": "2013, oil on board, 60 cm x 60 cm",
        "nameX": "The Robber is Upset",
        "descX": "2013, oil and spray on board, 37 cm x 50 cm",
        "nameX": "Juha is Guilty",
        "descX": "2013, oil and spray on board, 50 cm x 40 cm",
        "nameX": "UH",
        "descX": ", 2013, öljy kankaalle, 86 cm x 91 cm",
        "nameX": "Jaws",
        "descX": "2012, oil on board, 45 cm x 37 cm",
        "nameX": "Late",
        "descX": ", 2012, oil on board, 50 cm x 37 cm",
        "nameX": "Light Brown BMW",
        "descX": "2012, oil and spray on canvas, 25 cm x 33 cm",
        "nameX": "Back Seat",
        "descX": "2012, oil on board, 42 cm x 51 cm",
        "nameX": "Hunt",
        "descX": "2012, oil on canvas, 60 cm x 60 cm",
        "nameX": "A Hit",
        "descX": "2012, oil on board, 42 cm x 44 cm",
        "nameX": "Commando",
        "descX": "2012, oil on board, 42 cm x 29 cm",
        "nameX": "80 km/h",
        "descX": " 2012, oil and spray on board, 43 cm x 53 cm",
        "nameX": "At The House",
        "descX": "2012, oil and spray on board, 110 cm x 140 cm",
        "nameX": "The Sky",
        "descX": "2012, acrylic on canvas, 156 cm x 165 cm",
    },
    "fi": true
});


    